[env]
TERM = "xterm-256color"

[font]
size = 15
normal = { family = "RecMonoLinear Nerd Font", style = "normal" }
bold = { family = "RecMonoLinear Nerd Font", style = "Bold" }
italic = { family = "RecMonoLinear Nerd Font", style = "Italic" }

[window]
opacity = 1
dynamic_padding = false  # Ensures proper font rendering

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "xmodmap ~/.Xmodmap; exec zsh"]

[colors]
  [colors.primary]
  #foreground = "#ebdbb2"  # Cor de texto

  [colors.normal]
  black   = "#282828"  # cor do preto
  red     = "#fb4934"  # cor do vermelho
  green   = "#b8bb26"  # cor do verde
  yellow  = "#fbf16e"  # cor do amarelo
  blue    = "#83a598"  # cor do azul
  magenta = "#d3869b"  # cor do magenta
  cyan    = "#8ec07c"  # cor do ciano
  white   = "#ebdbb2"  # cor do branco
